from music21.note import Note

from .context import chantstats
from chantstats.v2.mode_degree import ModeDegree


def test_mode_degrees():
    assert 1 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("D3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("E3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("F3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("G3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("A3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("B3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("C3"))
    assert 1 == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("B-3"))

    assert 2 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("D3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("E3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("F3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("G3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("A3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("B3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("C3"))
    assert 2 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("B-3"))
    assert "flat-2" == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("A3"))

    assert 3 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("D3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("E3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("F3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("G3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("A3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("B3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("C3"))
    assert 3 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("B-3"))
    assert "flat-3" == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("G3"))

    assert 4 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("D3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("E3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("F3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("G3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("A3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("B3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("C3"))
    assert 4 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("B-3"))
    assert "flat-4" == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("F3"))

    assert 5 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("D3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("E3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("F3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("G3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("A3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("B3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("C3"))
    assert 5 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("B-3"))
    assert "flat-5" == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("E3"))

    assert 6 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("D3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("E3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("F3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("G3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("A3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("B3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("C3"))
    assert 6 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("B-3"))
    assert "flat-6" == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("D3"))

    assert 7 == ModeDegree.from_note_pair(note=Note("C3"), base_note=Note("D3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("D3"), base_note=Note("E3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("E3"), base_note=Note("F3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("F3"), base_note=Note("G3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("G3"), base_note=Note("A3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("B3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("B3"), base_note=Note("C3"))
    assert 7 == ModeDegree.from_note_pair(note=Note("A3"), base_note=Note("B-3"))
    assert "flat-7" == ModeDegree.from_note_pair(note=Note("B-3"), base_note=Note("C3"))
